name: health
description: تطبيق صحي متكامل

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  geolocator: ^10.1.0
  url_launcher: ^6.2.5
  google_maps_flutter: ^2.5.0  # <-- مضافة هنا

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
